### ISSUE TITLE
Breaking change in v0.2.3

### ISSUE THREAD

**Issue by tesaguri** [quininer/tokio-rustls#11]
In version `0.2.3`, you updated `rustls` from `^0.8` to `^0.9`. This is a breaking change and you should bump the minor version number.

The reason it is a breaking change is that `rustls ^0.8` depends on `ring ^0.9` and `rustls ^0.9` depends on `ring ^0.11`, and that `ring` does not allow you to link multiple versions of the crate into a binary (briansmith/ring#535).

**Comment by quininer** [comment]
You are right, I should be careful about this. Should I yank `0.2.3`?

**Comment by tesaguri** [comment]
I'd appreciate it if you could do so, but now that `hyper-rustls` depends on `tokio-rustls ^0.2.3`, yanking `0.2.3` right now would cause a breakage as well. So I don't mind if you won't yank it immediately.

**Comment by quininer** [comment]
well, I would like to wait for `rustls` next version.
