### ISSUE TITLE
Connections are abruptly closed in the event of a fatal error, in violation of spec

### ISSUE THREAD

**Issue by univerio** [quininer/tokio-rustls#12]
When a fatal error occurs, such as when TLS 1.2 is not supported by the client, or when the server fails to resolves an appropriate certificate, the connection is abruptly closed. The [RFC](https://tools.ietf.org/html/rfc5246#section-7.2.2) says that an error message must be sent prior to the connection being closed.

rustls attempts to send such a message, but the message gets queued and is promptly ignored by `TlsStream` before it closes the connection. The solution appears to be to flush the queue when an error is detected, but I'm not sure if this is the correct solution:

```
diff --git src/lib.rs src/lib.rs
index 4e3a47f..d4d1aa5 100644
--- src/lib.rs
+++ src/lib.rs
@@ -172,8 +172,16 @@ impl<S, C> TlsStream<S, C>
                         continue
                     },
                     Ok(_) => {
-                        self.session.process_new_packets()
-                            .map_err(|err| io::Error::new(io::ErrorKind::Other, err))?;
+                        if let Err(err) = self.session.process_new_packets() {
+                            // flush queued messages before returning an Err in
+                            // order to send alerts instead of abruptly closing
+                            // the socket
+                            if self.session.wants_write() {
+                                // ignore result to avoid masking original error
+                                let _ = self.session.write_tls(&mut self.io);
+                            }
+                            return Err(io::Error::new(io::ErrorKind::Other, err));
+                        }
                         continue
                     },
                     Err(ref e) if e.kind() == io::ErrorKind::WouldBlock => true,
```

**Comment by quininer** [comment]
This looks good, are you willing to open a PR?

**Comment by univerio** [comment]
The reason I'm not sure this is the correct solution is that rustls's [own code](https://github.com/ctz/rustls/blob/master/src/session.rs#L146-L147) doesn't seem to do this, so not sure whether you can safely still call `write_tls` after an error occurs. But given that the change only deals with error cases, and that the connection will be closed immediately thereafter anyway, perhaps this is okay.

If you're okay with this, I'd be happy to open a PR.

**Comment by quininer** [comment]
This may be an omission of rustls, maybe we should ask for @ctz.

**Comment by ctz** [comment]
Sorry, I missed this the first time around. You're right: it's both sensible and desirable to do a `write_tls` after the session fails like this -- and it's an omission that most of the rustls code doesn't do this.

**Comment by univerio** [comment]
Thanks @ctz. Would you like a similar PR for `complete_io` as well?
