### ISSUE TITLE
tokio-file-unix dependency causes build to fail on Windows

### ISSUE THREAD

**Issue by briansmith** [quininer/tokio-rustls#2]
Windows doesn't have tokio-file-unix. I suggest trying to use regular libstd file I/O like the Rustls examples use, to avoid depending on tokio-file-unix. This way tokio-rustls will work on Windows. This would make it easier for me to send PRs to your project.

**Comment by quininer** [comment]
I want to keep example asynchronous, using libstd I/O seems to make it much more complicated.

**Comment by briansmith** [comment]
OK, that makes sense. Do you have any preferred way to make it work on Windows?

**Comment by quininer** [comment]
~~Maybe I can add a feature to let Windows use libstd I/O.~~

>   Dev-dependencies are not allowed to be optional: `tokio-file-unix`

**Comment by quininer** [comment]
@briansmith I added a std-client, I think now it should work on Windows. https://github.com/quininer/tokio-rustls/commit/e597250fb875df7ec1f36b72de66a6af5f29a66f

**Comment by briansmith** [comment]
Thanks! Actually, the Windows build is still broken with that commit because the `#![cfg(unix)]` in client.rs means it doesn't define `fn main()`. I modified your fix to fix that in PR #3. I tested in both Linux and Windows.

I believe it isn't hard to make the stdin/stdout I/O non-blocking on Windows. That would be the proper fix, but I don't have time to do it now. I'll file an issue.

**Comment by briansmith** [comment]
This is fixed. Thanks!
