### ISSUE TITLE
Clarify the license

### ISSUE THREAD

**Issue by erickt** [quininer/tokio-rustls#29]
Hello,

The description of the license in the [README](https://github.com/quininer/tokio-rustls/blob/485cf8463989c25f0faa8d66c9c3dfdb7bce0063/README.md#license--origin) as added in #1 by @briansmith appears to be vague:

> tokio-rustls is primarily distributed under the terms of both the MIT license and the Apache License (Version 2.0), with portions covered by various BSD-like licenses.

* What part of tokio-rustls is covered by the BSD license? I could find no other reference to BSD in the tree.
* "primarily" seems to suggest that there portions that may not be covered by MIT and Apache. Could this be clarified?

It appears @briansmith may have got this phrase from some other rust projects, like futures-rs. They have since changed to using this [phrasing](https://github.com/rust-lang-nursery/futures-rs#license): 

```
# License
This project is licensed under either of

Apache License, Version 2.0, (LICENSE-APACHE or http://www.apache.org/licenses/LICENSE-2.0)
MIT license (LICENSE-MIT or http://opensource.org/licenses/MIT)
at your option.

### Contribution
Unless you explicitly state otherwise, any contribution intentionally submitted for inclusion in futures-rs by you, as defined in the Apache-2.0 license, shall be dual licensed as above, without any additional terms or conditions.
```

Would that be more along the lines of what you intended?

**Comment by erickt** [comment]
For context, here's the commit in futures-rs that explains why they switched the phrasing: https://github.com/rust-lang-nursery/futures-rs/commit/2d95ac92c46eb1f287bffe21f164362661fd0c24.

**Comment by quininer** [comment]
The new phrasing seems more reasonable. Would you like to submit a PR?
