### ISSUE TITLE
Consider renaming to futures-rustls

### ISSUE THREAD

**Issue by cramertj** [quininer/tokio-rustls#31]
This crate doesn't have any dependency on the tokio runtime today-- it'll work on any `futures`-compatible executor. At the moment it's rather hard to sort out which libraries are executor-agnostic and which are not. Would you consider renaming to help clarify this?

**Comment by quininer** [comment]
I have this idea! but I want there are some examples that run on other executors.

**Comment by cramertj** [comment]
Today `tokio` is the primary cross-platform executor. `tokio-rustls` also works with the Fuchsia executor, but I don't think it'd be appropriate to add an example for that since it's not something most people would be able to run, and it wouldn't be possible to check it in CI.

**Comment by quininer** [comment]
I have publish a `futures-rustls` crate as a placeholder on `crates.io` and I hope I can rename it in next version.

**Comment by quininer** [comment]
I changed the plan a little.

Originally I wanted to make `tokio-rustls` compatible with `tokio-io` and `futures-io`, but this is a bit complicated and redundant.

Now I decided to release `futures-rustls` for `futures-io` and continue to maintain `tokio-rustls` until tokio is fully migrated to futures 0.3.

**Comment by quininer** [comment]
[futures-rustls](https://crates.io/crates/futures-rustls/0.12.0-alpha) is already available.

**Comment by cramertj** [comment]
Awesome, thank you! :)
