### ISSUE TITLE
Can cert_resolver be async?

### ISSUE THREAD

**Issue by vpzomtrrfrt** [quininer/tokio-rustls#39]
My use case involves dynamically selecting a certificate based on SNI.  I see ServerConfig has a cert_resolver field, but it appears to be synchronous.  Is it possible to do this with a Future instead?

**Comment by quininer** [comment]
This is unlikely unless `rustls` provides a poll interface. But I think you can use a method like `tokio_threadpool::blocking` to increase the threadpool capacity to avoid block other threads.

**Comment by vpzomtrrfrt** [comment]
That's unfortunate, but I guess it'll work for now

**Comment by quininer** [comment]
I am closing it now, you can keep track it in https://github.com/ctz/rustls/issues/89.
