### ISSUE TITLE
Switch to Tokio 0.2

### ISSUE THREAD

**Issue by briansmith** [quininer/tokio-rustls#41]
See the Twitter thread https://twitter.com/seanmonstar/status/1148732643120275456. It would be great for tokio-rustls to use `std::future` so that the new `std::future`-based hyper can make use of it. I'm not sure what's all required to make that happen.

**Comment by quininer** [comment]
`tokio-rustls` already has a [branch](https://github.com/quininer/tokio-rustls/tree/futures-rustls) that supports `std::future`, but `tokio 0.2` doesn't seem to be using `futures-io`.

I will try to port it to `tokio 0.2` this weekend. https://github.com/quininer/tokio-rustls/issues/40

**Comment by briansmith** [comment]
@seanmonstar Do you have any suggestions for dealing with Tokio + `std::future` right now? I imagine you must have already solved it to get Hyper working with `std::future`.

**Comment by seanmonstar** [comment]
So far in hyper, I've just been using `tokio_io::{AsyncRead, AsyncWrite}`.

**Comment by DoumanAsh** [comment]
afaik I remember Carl mentioning that he is not sure what to do with `AsyncRead` and `AsyncWrite` so for now they left it in `tokio-io` so it can go either like that or eventually it will alias `futures`'s traits

**Comment by quininer** [comment]
I have built a [tokio 0.2](https://github.com/quininer/tokio-rustls/tree/tokio-0.2) branch.

**Comment by quininer** [comment]
I have built a [tokio 0.2](https://github.com/quininer/tokio-rustls/tree/tokio-0.2) branch.

**Comment by CryZe** [comment]
I ported hyper-rustls to use this branch and everything seems to be working :D

**Comment by DoumanAsh** [comment]
@quininer btw Carl removed `tokio-futures` and now they just re-export from futures crate

**Comment by quininer** [comment]
`tokio-rustls 0.12.0` has been released.
