### ISSUE TITLE
Make stdin/stdout I/O in examples/client.rs non-blocking on Windows too.

### ISSUE THREAD

**Issue by briansmith** [quininer/tokio-rustls#5]
Setting stdin/stdout to non-blocking is done in a unix-specific way now, so stdin/stdout are read/written in a blocking manner on Windows. However, it shouldn't be too hard to make stdin/stdout non-blocking on Windows too, so that all target platforms can share one code path.

**Comment by quininer** [comment]
I always wanted a cross-platform `tokio-file`, but I don't know about Windows.

**Comment by quininer** [comment]
I updated the client example, which use tokio-fs on Windows, but it does not seem to behave as expected.
