### ISSUE TITLE
Bind multiple tls on the same port

### ISSUE THREAD

**Issue by ghost** [quininer/tokio-rustls#58]
May I ask if there is a way to bind multiple sites on port 443, I have multiple certificates.

```rust
while let Ok ((stream, _)) = listener.accept().await {

    if let Ok(tls_stream) = tls1.accept(stream).await {
        // https://example1.com
    }

    if let Ok(tls_stream) = tls2.accept(stream).await {
        // https://example1.com
    }

}
```

Related issues: #42 

Thank you for creating this crate.

**Comment by quininer** [comment]
I think you can use [ResolvesServerCertUsingSNI](https://docs.rs/rustls/0.16.0/rustls/struct.ResolvesServerCertUsingSNI.html) to choose different certificates for different sni, and use [get_sni_hostname](https://docs.rs/rustls/0.16.0/rustls/struct.ServerSession.html#method.get_sni_hostname) in `TlsStream` to distinguish different sites.

**Comment by ghost** [comment]
The problem has been resolved, thank you for your reply
