### ISSUE TITLE
How can I solve client request pending in the tokio-rustls version of 0.10.2.

### ISSUE THREAD

**Issue by lixiaodongcq** [quininer/tokio-rustls#61]
i meet the problem like issue of https://github.com/quininer/tokio-rustls/issues/55,
i do not want  to upgrade tokio-rustls， how can i solve this problem in 0.10.2 ?

**Comment by quininer** [comment]
I will try backport this fix later. ：）

**Comment by lixiaodongcq** [comment]
Thank you very much!

**Comment by quininer** [comment]
I just released 0.10.3. Anyway I suggest you upgrade to 0.12.

**Comment by lixiaodongcq** [comment]
Thanks!  Can i get the version of 0.10.3 now ?

**Comment by quininer** [comment]
Yes, see https://crates.io/crates/tokio-rustls/0.10.3

**Comment by lixiaodongcq** [comment]
Hello, When i use 0.10.3,  there is some improvement in the request pending, but sometimes pending occurs, can you continue to optimize it based on 0.10.3?
