### ISSUE TITLE
Hello, When i use 0.10.3,  sometimes pending occurs.

### ISSUE THREAD

**Issue by lixiaodongcq** [quininer/tokio-rustls#62]
Hello, When i use 0.10.3, there is some improvement in the request pending, but sometimes pending occurs, can you continue to optimize it based on 0.10.3?

**Comment by quininer** [comment]
Can you provide a reproducible code or describe the problem in detail?

**Comment by lixiaodongcq** [comment]
I use tokio_rustls as the https server. The conditions that occur are occasional. When there are some requests, the server does not accept the requests. When the netstat command is called, I find that the server has more close_wait states. But it may recover again after a while。

**Comment by quininer** [comment]
This sounds completely unrelated to #61 because it only affects clients with 0-RTT turned on.

Will you have the same problem if you try to use tokio-tls or not use tls?

**Comment by lixiaodongcq** [comment]
Is tokio-tls support client auth?

**Comment by quininer** [comment]
I think it supports, see https://docs.rs/native-tls/0.2.3/native_tls/struct.TlsConnectorBuilder.html#method.identity .

**Comment by quininer** [comment]
Do you use irc or matrix? We can directly chat.

**Comment by lixiaodongcq** [comment]
Sorry.  It's my fault.  I just can not find how to add root cert in sever to authority client cert in tokio-tls

**Comment by lixiaodongcq** [comment]
Sorry I just use qq or wechat

**Comment by quininer** [comment]
I think you are looking for [add_root_certificate](https://docs.rs/native-tls/0.2.3/native_tls/struct.TlsConnectorBuilder.html#method.add_root_certificate) instead of client auth.

Anyway, I don't think github issue is a proper place.
