### ISSUE TITLE
Additional trait implementations for TlsStream

### ISSUE THREAD

**Issue by nickbabcock** [quininer/tokio-rustls#7]
I think I'm having a tough time using this library in all the places I'm using the other tokio code and I think it's because the Tokio `TcpStream` has additional trait implementations.

```rust
impl<'a> Read for &'a TcpStream {
}

impl<'a> Write for &'a TcpStream {
}

impl<'a> AsyncRead for &'a TcpStream {
}

impl<'a> AsyncWrite for &'a TcpStream {
}
```

I noticed that `TlsStream` doesn't implement the same traits with reference lifetime parameters. Does it make sense to implement these?

**Comment by quininer** [comment]
The crate API should be similar to [tokio-tls](https://github.com/tokio-rs/tokio-tls).

**Comment by nickbabcock** [comment]
Yeah, I was just interested in why there is a discrepancy between what's implemented for `TcpStream` and what's implemented for `TlsStream`, as it's currently over my head. If you think this question is more appropriate for the `tokio-tls` repo, I can post there.

**Comment by briansmith** [comment]
@nickbabcock I think it's worth trying to do it. Maybe @ctz could tell you whether those specific traits make sense.

**Comment by quininer** [comment]
stale
