### ISSUE TITLE
Support to set buffer limit of sessions

### ISSUE THREAD

**Issue by pzread** [quininer/tokio-rustls#9]
If the `write_tls` is blocked because the under layer I/O is blocking (e.g. network buffer is full), since the default buffer limit is unlimited, according to

> This buffer is of unlimited size so writing much data before it can be sent will cause excess memory usage.

Keep `write` plaintext data to the session will still success but unlimited buffered in the memory, and cause OOM. I think it will be better to provide a way to set buffer limit by session's method `set_buffer_limit`.

BTW, the current `write` loop logic will become a infinite loop when the buffer is limited. It seems that if the internal buffer of rustls is full, the `write` will return `Ok(0)`

**Comment by quininer** [comment]
`TlsStream` support `get_mut`, should be able to `tls_stream.get_mut().1.set_buffer_limit(size)`.

Maybe we should provide a `{connect,accept}_async_with_session()`?

**Comment by pzread** [comment]
Oh, I missed that method. But the `write` loop logic still need to fix.

I think it's a good idea, let users config sessions by themselves. But the user may mess up the session then pass it to `xxx_async_with_session`, don't know what will happen.

**Comment by quininer** [comment]
Sounds good, are you willing to open a PR?

**Comment by pzread** [comment]
Sure
